name: deploy-prod
on:
  pull_request:
    # push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: install yarn
        run: yarn install --frozen-lockfile

      - name: deploy
        run: |
          npm i -g aws-cdk@1.70.0
          touch .env
          cd packages/fullstack-cli
          npm i -g .
          cd ../..
          fs deploy
        env:
          STACK_NAME: fullstack-production
          NODE_ENV: production
          ES_URL: ${{ secrets.PROD_ES_URL }}
          ES_USERNAME: ${{ secrets.PROD_ES_USERNAME }}
          ES_PASSWORD: ${{ secrets.PROD_ES_PASSWORD }}
          SES_REGION: eu-west-1
          TOPIC_ARN: dummy
          BLOG_DOMAIN: fullstack.pl,blog.fullstack.pl
          DOMAIN_CERT: arn:aws:acm:us-east-1:761975498781:certificate/02c0ca60-e3bc-4cab-a15c-2443541e2a3c
